### PR TITLE
Added rules for logging

### PR DESCRIPTION
**Pull request by DirkMahler**

### CODE REVIEW

**Comment by Rensykes** [comment]
Hello Dirk,
I still have a green build even if I have log4j2 as dependency. I think that occurs because, as far as I understand, the check is performed only on the type but not on the dependencies. So, if I use **log4j2 behind the slf4j facade**, it is still considered valid.
Isn't it possible to perform a check on the dependency tree?

Also, I saw you removed some stuff from the jqassistant.yml but in another project, the one where we already had jqassistant in place, we have a huge set of rules related to tests. Will I be able to merge the twos? Can I eventually ask for your help in understand how to do it? It's not my main goal right now, so I will focus more on the constraints about logging.

**Comment by DirkMahler** [comment]
@Rensykes I added another constraint for validating dependencies, please verify if this is what you need.

**Comment by DirkMahler** [comment]
For the change to `.jqassistant.yml`: I adopted to it to fit the "usual" setup, but there might be reasons for the other settings where I would need to context to judge if they are necessary or not.

**Comment by Rensykes** [comment]
> For the change to `.jqassistant.yml`: I adopted to it to fit the "usual" setup, but there might be reasons for the other settings where I would need to context to judge if they are necessary or not.

@DirkMahler I added 

`
jqassistant:
  analyze:
    report:
      warn-on-severity: MINOR
      fail-on-severity: MINOR
`

so that the build fails on the failure of some of the constraints and concepts. 

The problem is that now I get 3 concepts failing even though I have some instances, for example, of org.slf4j.Logger and org.slf4j.LoggerFactory:


```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
public class StammdatenEditorService {

  private static final Logger LOGGER = LoggerFactory.getLogger(StammdatenEditorService.class);
}
```


> [ERROR] --[ Concept Application Failure ]----------------------------------
> [ERROR] Concept: logging:LogbackLogger
> [ERROR] Severity: MINOR
> [ERROR] Number of rows: 0
> [ERROR] Identifies the Logback loggers used in the application
> [ERROR] -------------------------------------------------------------------
> [ERROR] 
> [ERROR] --[ Concept Application Failure ]----------------------------------
> [ERROR] Concept: logging:Logger
> [ERROR] Severity: MINOR
> [ERROR] Number of rows: 0
> [ERROR] Identifies the loggers used in the application
> [ERROR] -------------------------------------------------------------------
> [ERROR] 
> [ERROR] --[ Concept Application Failure ]----------------------------------
> [ERROR] Concept: logging:Slf4jLogger
> [ERROR] Severity: MINOR
> [ERROR] Number of rows: 0
> [ERROR] Identifies the Slf4j loggers used in the application
> [ERROR] -------------------------------------------------------------------

**Comment by DirkMahler** [comment]
This means the database is empty. Did you execute a scan?

**Comment by Rensykes** [comment]
> This means the database is empty. Did you execute a scan?

@DirkMahler I performed a mvn clean, then mvn jqassistant:scan and mvn jqassistant:analyze

**Comment by DirkMahler** [comment]
> > This means the database is empty. Did you execute a scan?
> 
> @DirkMahler I performed a mvn clean, then mvn jqassistant:scan and mvn jqassistant:analyze

Please run `mvn verify -Pjqassistant`

**Comment by Rensykes** [comment]
> mvn verify -Pjqassistant

Running this, only Concept: logging:LogbackLogger fails. I suppose this and logging:Slf4jLogger should be in OR since you use Slf4J most of the times and very rarely you actually declare a Logback logger.

Also, could you explain to me what changed when I ran `mvn verify -Pjqassistant` instead of the aforementioned commands?

**Comment by DirkMahler** [comment]
> > mvn verify -Pjqassistant
> 
> Running this, only Concept: logging:LogbackLogger fails. I suppose this and logging:Slf4jLogger should be in OR since you use Slf4J most of the times and very rarely you actually declare a Logback logger.

The idea is to provide concepts to identify logging frameworks that might (intentionally or accidentially) be used in the code. These can be extended by Commons Logging or Java Util Logging, etc. Usually such kind of concepts would be lower in severity such that they do not generate a warning.
 
> Also, could you explain to me what changed when I ran `mvn verify -Pjqassistant` instead of the aforementioned commands?

`mvn verify` builds the project (i.e. including compile, etc.), the profile `jqassistant` is configured in your pom.xml to execute `scan` and `analyze` (that's a standard setup).

**Comment by Rensykes** [comment]
> the profile jqassistant is configured in your pom.xml to execute scan and analyze (that's a standard setup).

That I understand. Maybe the problem was that only a clean was performed and not all the others lifecycle operations.

> I suppose this and logging:Slf4jLogger should be in OR

Would that be possibile? I think the best solution would be to make only one concept instead of two separate that matches both a logger of type org.slf4j.Logger or a logger of type ch.qos.logback.classic.Logger


Also, I think that in the constraint logging:Slf4jMustBeUsedForLogging, the right required concepts should be 
```
        <requiresConcept refId="logging:LogbackLogger"/>
        <requiresConcept refId="logging:Slf4jLogger"/>
```

instead of 
```
        <requiresConcept refId="logging:Logger"/>
        <requiresConcept refId="logging:Slf4jLogger"/>
```

**Comment by Rensykes** [comment]
I was thinking about something like this:

 ```
<constraint id="logging:Slf4jMustBeUsedForLogging" severity="blocker">
        <requiresConcept refId="logging:LogbackLogger"/>
        <requiresConcept refId="logging:Slf4jLogger"/>
        <description>Slf4j logger must be used for logging</description>
        <cypher><![CDATA[
            MATCH
              (type:Type)-[:DECLARES]->(method:Method)-[invocation:INVOKES]->(:Method)<-[:DECLARES]-(logger:Type:Logger)
            WHERE NOT
              logger:Slf4j OR logger:Logback
            RETURN
              type as Type, invocation as Invocation, logger as InvalidLogger
            ORDER BY
              invocation.lineNumber
        ]]>
        </cypher>
        <report primaryColumn="Invocation"/>
    </constraint>

    <concept id="logging:Logger">
        <description>Identifies the loggers used in the application</description>
        <cypher><![CDATA[
            MATCH
              (logger:Type:Logger)
            RETURN
              logger
            ORDER BY
              logger.fqn
        ]]>
        </cypher>
    </concept>

    <concept id="logging:Slf4jLogger">
        <providesConcept refId="logging:Logger"/>
        <description>Identifies the Slf4j loggers used in the application</description>
        <cypher><![CDATA[
            MATCH
              (logger:Type{fqn:"org.slf4j.Logger"})
            SET
              logger:Logger:Slf4j
            RETURN
              logger
            ORDER BY
              logger.fqn
        ]]>
        </cypher>
    </concept>

    <concept id="logging:LogbackLogger">
        <providesConcept refId="logging:Logger"/>
        <description>Identifies the Logback loggers used in the application</description>
        <cypher><![CDATA[
            MATCH
              (logger:Type{fqn:"ch.qos.logback.classic.Logger"})
            SET
              logger:Logger:Logback
            RETURN
              logger
            ORDER BY
              logger.fqn
        ]]>
        </cypher>
    </concept>
```

and 

```
jqassistant:
  analyze:
    report:
      warn-on-severity: MINOR
      fail-on-severity: BLOCKER
    groups:
      - logging
    execute-applied-concepts: true
```

But doing so , when I run `mvn verify -Pjqassistant -DskipTests` build is successful but I see this entry in the log

> [WARNING] Neo.ClientNotification.Statement.UnknownLabelWarning - The provided label is not in the database.: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Logback) (at 5:38)

**Comment by DirkMahler** [comment]
> > the profile jqassistant is configured in your pom.xml to execute scan and analyze (that's a standard setup).
> 
> That I understand. Maybe the problem was that only a clean was performed and not all the others lifecycle operations.
> 
> > I suppose this and logging:Slf4jLogger should be in OR
> 
> Would that be possibile? I think the best solution would be to make only one concept instead of two separate that matches both a logger of type org.slf4j.Logger or a logger of type ch.qos.logback.classic.Logger
> 
> Also, I think that in the constraint logging:Slf4jMustBeUsedForLogging, the right required concepts should be
> 
> ```
>         <requiresConcept refId="logging:LogbackLogger"/>
>         <requiresConcept refId="logging:Slf4jLogger"/>
> ```
> 
> instead of
> 
> ```
>         <requiresConcept refId="logging:Logger"/>
>         <requiresConcept refId="logging:Slf4jLogger"/>
> ```

That's by intention: "logging:Logger" is an abstract concept that is provided by the concrete concepts "logging:LogbackLogger" and "logging:Slf4jLogger". They are implicitly executed if a rule requires "logging:Logger".
So if another logging framework comes into scope to be excluded then just add another concept providing it using the label Logger in combination with specific label like JUL or JCL, etc.

**Comment by Rensykes** [comment]
> That's by intention: "logging:Logger" is an abstract concept that is provided by the concrete concepts "logging:LogbackLogger" and "logging:Slf4jLogger". They are implicitly executed if a rule requires "logging:Logger".

Then why you explictely added 

`        <requiresConcept refId="logging:Slf4jLogger"/>
`

Shouldn't it be implicitely executed?


Also, I still receive 

> [WARNING] Neo.ClientNotification.Statement.UnknownLabelWarning - The provided label is not in the database.: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Logback) (at 5:38)

Does this happen because it can't find any occurrence of Logback?

**Comment by DirkMahler** [comment]
> > That's by intention: "logging:Logger" is an abstract concept that is provided by the concrete concepts "logging:LogbackLogger" and "logging:Slf4jLogger". They are implicitly executed if a rule requires "logging:Logger".
> 
> Then why you explictely added
> 
> ` <requiresConcept refId="logging:Slf4jLogger"/>`
> 
> Shouldn't it be implicitely executed?

Correct. But it is considered a best practice to make the required concepts for a rule explicit: in this case Logger (not matte which one) and Slf4j. So this is just for readability.

> Also, I still receive
> 
> > [WARNING] Neo.ClientNotification.Statement.UnknownLabelWarning - The provided label is not in the database.: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Logback) (at 5:38)
> 
> Does this happen because it can't find any occurrence of Logback?

Correct as well.

**Comment by Rensykes** [comment]
> Correct. But it is considered a best practice to make the required concepts for a rule explicit: in this case Logger (not matte which one) and Slf4j. So this is just for readability.

Ok clear. Just one last question: would it be possibile to change the 

```
<constraint id="logging:Slf4jMustBeUsedForLogging">
       <requiresConcept refId="logging:Logger"/>
       <requiresConcept refId="logging:Slf4jLogger"/>
       <description>Slf4j logger must be used for logging</description>
       <cypher><![CDATA[
           MATCH
             (type:Type)-[:DECLARES]->(method:Method)-[invocation:INVOKES]->(:Method)<-[:DECLARES]-(logger:Type:Logger)
           WHERE NOT
             logger:Slf4j
           RETURN
             type as Type, invocation as Invocation, logger as InvalidLogger
           ORDER BY
             invocation.lineNumber
       ]]>
       </cypher>
       <report primaryColumn="Invocation"/>
   </constraint>
```

to check whether the declared loggers are either Slf4j OR Logback?

Something like this:

```
<constraint id="logging:Slf4jMustBeUsedForLogging">
       <requiresConcept refId="logging:Logger"/>
       <requiresConcept refId="logging:Slf4jLogger"/>
       <description>Slf4j logger must be used for logging</description>
       <cypher><![CDATA[
           MATCH
             (type:Type)-[:DECLARES]->(method:Method)-[invocation:INVOKES]->(:Method)<-[:DECLARES]-(logger:Type:Logger)
           WHERE NOT
             logger:Slf4j OR logger:Logback
           RETURN
             type as Type, invocation as Invocation, logger as InvalidLogger
           ORDER BY
             invocation.lineNumber
       ]]>
       </cypher>
       <report primaryColumn="Invocation"/>
   </constraint>
```

**Comment by DirkMahler** [comment]
Exactly this: 

```
 WHERE NOT
  logger:Slf4j OR logger:Logback
```

**Comment by Rensykes** [comment]
So this warning 

> [WARNING] Neo.ClientNotification.Statement.UnknownLabelWarning - The provided label is not in the database.: One of the labels in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing label name is: Logback) (at 5:38)

appears just because we don't have an actual declared Logback logger. But in application that does have it, this warning should not appear, right?

**Comment by DirkMahler** [comment]
That's correct. We'll add a feature to suppress these warnings (they're actually only there to debug rules)

**Comment by Rensykes** [comment]
> That's correct. We'll add a feature to suppress these warnings (they're actually only there to debug rules)

Oh ok! Perfect! I think we reached a point where I'm happy with it! I'll close the PR and you can answer to the stackoverflow question. 

Now it will come the hard part, integrating with the applications that already have jqassistant implemented (an older version) and hope everything goes fine =)

Thanks again for your support and of course you can use this repo as an example repo for jqassistant for this purpose =)

**Comment by Rensykes** [comment]
@DirkMahler I actually noticed that the OR does not work and I get failures such as 

> [ERROR] Constraint: logging:Slf4jMustBeUsedForLogging
> [ERROR] Severity: MAJOR
> [ERROR] Number of rows: 36
> [ERROR]
> [ERROR] Slf4j logger must be used for logging
> [ERROR]
> [ERROR] Type=com.myapp.LoggerUtilTest, Invocation=void <init>(), line 25, InvalidLogger=ch.qos.logback.classic.Logger
> [ERROR] Type=com.myapp.LoggerUtil, Invocation=ch.qos.logback.classic.Logger setLogLevel(java.lang.String,java.lang.String), line 27, InvalidLogger=ch.qos.logback.classic.Logger


**LoggerUtilTest**

```
class LoggerUtilTest {

  @Mock private Appender<ILoggingEvent> mockedAppender = Mockito.mock(Appender.class);
  private final String basePackage = "com.myapp";

  private final String childPackage =
      LoggerUtil.getContextLoggers().stream()
          .map(Logger::getName)
          .filter(name -> name.startsWith(basePackage))
          .reduce((first, second) -> second)
          .orElse(null);

  private final String wrongPackage = "com.myapp.wrong.package";

  @BeforeEach
  void setup() {
    LoggerUtil.getContextLoggers().forEach((logger -> logger.addAppender(mockedAppender)));
  }

  @Test
  void setLogLevel_shouldChangeLevel_whenLoggerExistsAndHasInfoLevel() {
    checkLogLevelChange(childPackage, Level.INFO);
    checkLogLevelChange(childPackage, Level.DEBUG);
  }

  @Test
  void setLogLevel_shouldChangeAlsoChildrenLoggersLevel_whenChildrenLoggersExistAndHaveInfoLevel() {
    checkLogLevelChange(basePackage, Level.INFO);
    checkChildrenLogLevelChange(Level.INFO);

    checkLogLevelChange(basePackage, Level.DEBUG);
    checkChildrenLogLevelChange(Level.DEBUG);
  }

  @Test
  void setLogLevel_shouldNotChangeLevel_whenLoggerDoesntExists() {
    checkMissingParameters(wrongPackage, "DEBUG");
  }

  @Test
  void setLogLevel_shouldNotChangeLevel_whenLoggerNameIsNull() {
    checkMissingParameters(null, "DEBUG");
  }

  @Test
  void setLogLevel_shouldNotChangeLevel_whenLevelIsNull() {
    checkMissingParameters(basePackage, null);
  }

  private void checkLogLevelChange(String loggerName, Level level) {
    Logger logger = LoggerUtil.setLogLevel(loggerName, level.toString());
    assertEquals(loggerName, logger.getName());
    assertEquals(level, logger.getLevel());
  }

  private void checkChildrenLogLevelChange(Level level) {
    LoggerUtil.getContextLoggers().stream()
        .filter(contextLogger -> LoggerUtil.isLoggerConfigured(contextLogger, basePackage))
        .forEach(logger -> assertEquals(level, logger.getLevel()));
  }

  private void checkMissingParameters(String loggerName, String level) {
    Logger logger = LoggerUtil.setLogLevel(loggerName, level);
    assertNull(logger);
  }
}

```

**LoggerUtil**

```
package com.myapp.application.common.util;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import java.util.List;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.LoggerFactory;

public final class LoggerUtil {

  /** The logger for this class. */
  private static final org.slf4j.Logger LOGGER = LoggerFactory.getLogger(LoggerUtil.class);

  private LoggerUtil() {}

  public static Logger setLogLevel(String loggerName, String nextLevelStr) {
    Logger logger = null;
    if (!StringUtils.isEmpty(loggerName) && !StringUtils.isEmpty(nextLevelStr)) {
      List<String> loggersToSet =
          getContextLoggers().stream()
              .filter(contextLogger -> isLoggerConfigured(contextLogger, loggerName))
              .map(Logger::getName)
              .distinct()
              .toList();

      if (!CollectionUtils.isEmpty(loggersToSet)) {
        for (String loggerToSet : loggersToSet) {
          logger = (Logger) LoggerFactory.getLogger(loggerToSet);
          Level nextLevel = Level.toLevel(nextLevelStr);
          logger.setLevel(nextLevel);

          LOGGER.info("Set logger {} to {}.", loggerToSet, nextLevel.toString());
        }

        logger =
            loggersToSet.contains(loggerName)
                ? (Logger) LoggerFactory.getLogger(loggerName)
                : (Logger) LoggerFactory.getLogger(loggersToSet.stream().findFirst().get());
      }
    }
    return logger;
  }

  public static List<Logger> getContextLoggers() {
    LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
    return loggerContext.getLoggerList();
  }

  public static boolean isLoggerConfigured(Logger contextLogger, String loggerName) {
    return contextLogger.getName().equals(loggerName)
        || (contextLogger.getName().startsWith(loggerName)
            && contextLogger.iteratorForAppenders().hasNext());
  }
}
```

I took those two just as examples

**Comment by DirkMahler** [comment]
The condition is missing some parenthesis:

```
 ...
 WHERE NOT (
   logger:Slf4j OR logger:Logback
 )  
...
```

**Comment by Rensykes** [comment]
Looks perfect! @DirkMahler

**Pull request merged**
